### ISSUE TITLE
Failed to submit aab because the file is still in processing

### ISSUE THREAD

**Issue by minkiapps** [shr3jn/fastlane-plugin-huawei_appgallery_connect#20]
After trying to use your latest plugin update with aab upload, I get error when trying to submit

this is my lane file
```
desc "Deploy a new release version to the Huawei App Gallery Connect"
      lane :deployBundleHuaweiRelease do
        huawei_appgallery_connect(
            client_id: "423532452345",
            client_secret: "43253245324523452345",
            app_id: "23453245",
            apk_path: "/Users/mingkangpan/Documents/minki/code/android/cardcreator/app/build/outputs/bundle/release/app-release.aab",
            is_aab: true
        )
      end
```

this is the error
`{"ret"=>{"code"=>204144660, "msg"=>"[cds]submit failed, additional msg is [The pkg: [release.aab] is being processed. It may take 2-5 minutes, depending on the size of the software package.]"}}`

Have you faced this issue before with apk upload?

**Comment by shr3jn** [comment]
Set submit_for_review to false and execute another lane submit_for _review after a delay of around 5 mins.

**Comment by minkiapps** [comment]
Hey, sorry for being annoying..

Could you add a poll mechanism after aab is uploaded and poll every 30 seconds for aab processing status? So you can submit the app afterwards.
It is inconvenient if you think every CI has to add an extra step to submit.

I would do it myself and make a PR, but I have never programmed ruby before.. :-/

**Comment by shr3jn** [comment]
Ok will add this on future release.

**Comment by minkiapps** [comment]
thank you in name of Huawei and community :D 
As soon as this is done, I can proudly tell others that they can use their beloved Fastlane also for App Gallery App Bundle!

**Comment by shr3jn** [comment]
this is done but there is one issues, there is no way to identify if the build is processing as Huawei is returning same error code, so I'm need to think before releasing:

**When build is processing:**
{"ret"=>{"code"=>204144660, "msg"=>"[cds]submit failed, additional msg is [The pkg: [release.aab] is being processed. It may take 2-5 minutes, depending on the size of the software package.]"}}

**Some other error:**
 {"ret"=>{"code"=>204144660, "msg"=>"[cds]submit failed, additional msg is [Dist country is required.]"}}

**Comment by shr3jn** [comment]
I guess i will just match the error message as well... let me see

**Comment by minkiapps** [comment]
wait, there is an API from Huawei to ask the aab processing status, give me one minute to find the link

**Comment by minkiapps** [comment]
https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-References/agcapi-query-aabfile_v2
this is what you need

**Comment by shr3jn** [comment]
> https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-References/agcapi-query-aabfile_v2
> this is what you need

thanks, this api is what i need 👍 

but for now i've just gone for a simple solution, please test v1.0.14, will integrate that api some time in the future, for now 1.0.14 should work.

**Comment by shr3jn** [comment]
yes sure, your CI pipeline should also have execution time limit.

**Comment by minkiapps** [comment]
thanks, yeah usually CI pipeline have that anyway... but for people like me, who only uses the terminal :D

**Comment by minkiapps** [comment]
hey, even though with your changes I could automate the submit_for_review after uploading the aab, but still i get a weird error in terminal 

```
fastlane finished with errors

[!] {"ret"=>{"code"=>204144647, "msg"=>"[cds]update service failed, additional msg is [The new service has can't be edited service,which can't be updated!]"}}
```

**Comment by shr3jn** [comment]
@minkiapps Can you post on Huawei forums and ask them what causes this issue?

**Comment by minkiapps** [comment]
I will, do you have time maybe to change the implementation to pooling of bundle processing status?

**Comment by shr3jn** [comment]
Yes, will do that soon.

**Comment by shr3jn** [comment]
@minkiapps added aab compilation status check before submitting aab for review.

**Comment by minkiapps** [comment]
hey, it's working basically still, I am retrieving error in the terminal, can you tell me which request is throwing back this error?
```
fastlane finished with errors

[!] {"ret"=>{"code"=>204144647, "msg"=>"[cds]update service failed, additional msg is [The new service has can't be edited service,which can't be updated!]"}}
```

I can't really see the logs and or don't know how to see it...

**Comment by shr3jn** [comment]
Please post which step you've reached before this error is triggered.
(Post full log)

**Comment by minkiapps** [comment]
I did fastlane --verbose

```
INFO [2020-11-02 16:42:13.85]: Cruising over to lane 'android uploadBundleHuaweiRelease' 🚖
INFO [2020-11-02 16:42:13.85]: ---------------------------------------
INFO [2020-11-02 16:42:13.85]: --- Step: huawei_appgallery_connect ---
INFO [2020-11-02 16:42:13.85]: ---------------------------------------
WARN [2020-11-02 16:42:13.85]: Fetching app access token
INFO [2020-11-02 16:42:14.61]: Fetching upload URL
WARN [2020-11-02 16:42:15.57]: Uploading app
INFO [2020-11-02 16:42:29.74]: Upload app to AppGallery Connect successful
WARN [2020-11-02 16:42:29.74]: Saving app information
INFO [2020-11-02 16:42:33.74]: App information saved.
WARN [2020-11-02 16:42:33.74]: Checking aab compilation status
WARN [2020-11-02 16:42:34.43]: aab file is currently processing, waiting for 2 minutes...
WARN [2020-11-02 16:42:44.44]: Checking aab compilation status
WARN [2020-11-02 16:42:45.45]: aab file is currently processing, waiting for 2 minutes...
WARN [2020-11-02 16:42:55.45]: Checking aab compilation status
WARN [2020-11-02 16:42:56.09]: aab file is currently processing, waiting for 2 minutes...
WARN [2020-11-02 16:43:06.10]: Checking aab compilation status
WARN [2020-11-02 16:43:06.84]: aab file is currently processing, waiting for 2 minutes...
WARN [2020-11-02 16:43:16.84]: Checking aab compilation status
WARN [2020-11-02 16:43:17.57]: aab file is currently processing, waiting for 2 minutes...
WARN [2020-11-02 16:43:27.57]: Checking aab compilation status
WARN [2020-11-02 16:43:28.31]: aab file is currently processing, waiting for 2 minutes...
WARN [2020-11-02 16:43:38.32]: Checking aab compilation status
WARN [2020-11-02 16:43:39.17]: Submitting app for review
INFO [2020-11-02 16:43:40.78]: Successfully submitted app for review
INFO [2020-11-02 16:43:40.78]: Cruising back to lane 'android deployBundleRelease' 🚘
INFO [2020-11-02 16:43:40.78]: ---------------------------------------------------
INFO [2020-11-02 16:43:40.78]: --- Step: Switch to android submitAppOnAGC lane ---
INFO [2020-11-02 16:43:40.78]: ---------------------------------------------------
INFO [2020-11-02 16:43:40.78]: Cruising over to lane 'android submitAppOnAGC' 🚖
INFO [2020-11-02 16:43:40.78]: ---------------------------------------------------------
INFO [2020-11-02 16:43:40.78]: --- Step: huawei_appgallery_connect_submit_for_review ---
INFO [2020-11-02 16:43:40.78]: ---------------------------------------------------------
WARN [2020-11-02 16:43:40.78]: Fetching app access token
WARN [2020-11-02 16:43:41.14]: Submitting app for review
WARN [2020-11-02 16:43:42.14]: Lane Context:
INFO [2020-11-02 16:43:42.14]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android deployBundleRelease", "VERSION_CODE"=>6, :GRADLE_ALL_APK_OUTPUT_PATHS=>[], :GRADLE_ALL_AAB_OUTPUT_PATHS=>["/Users/mingkangpan/Documents/minki/code/android/Instant-Translator/app/build/outputs/bundle/release/app-release.aab"], :GRADLE_ALL_OUTPUT_JSON_OUTPUT_PATHS=>[], :GRADLE_ALL_MAPPING_TXT_OUTPUT_PATHS=>["/Users/mingkangpan/Documents/minki/code/android/Instant-Translator/app/build/outputs/mapping/release/mapping.txt"], :GRADLE_AAB_OUTPUT_PATH=>"/Users/mingkangpan/Documents/minki/code/android/Instant-Translator/app/build/outputs/bundle/release/app-release.aab", :GRADLE_MAPPING_TXT_OUTPUT_PATH=>"/Users/mingkangpan/Documents/minki/code/android/Instant-Translator/app/build/outputs/mapping/release/mapping.txt"}
ERROR [2020-11-02 16:43:42.14]: {"ret"=>{"code"=>204144647, "msg"=>"[cds]update service failed, additional msg is [The new service has can't be edited service,which can't be updated!]"}}
INFO [2020-11-02 16:43:42.14]: Successfully generated documentation at path '/Users/mingkangpan/Documents/minki/code/android/Instant-Translator/fastlane/README.md'

+------+--------------------------------------------+-------------+
|                        fastlane summary                         |
+------+--------------------------------------------+-------------+
| Step | Action                                     | Time (in s) |
+------+--------------------------------------------+-------------+
| 1    | default_platform                           | 0           |
| 2    | Switch to android makeReleaseBundle lane   | 0           |
| 3    | increment_version_code                     | 0           |
| 4    | commit_android_version_bump                | 0           |
| 5    | clean bundleRelease                        | 7           |
| 6    | Switch to android                          | 0           |
|      | uploadBundleHuaweiRelease lane             |             |
| 7    | huawei_appgallery_connect                  | 86          |
| 8    | Switch to android submitAppOnAGC lane      | 0           |
| 💥   | huawei_appgallery_connect_submit_for_revi  | 1           |
|      | ew                                         |             |
+------+--------------------------------------------+-------------+

DEBUG [2020-11-02 16:43:42.16]: All plugins are up to date
ERROR [2020-11-02 16:43:42.16]: fastlane finished with errors
DEBUG [2020-11-02 16:43:42.16]: All plugins are up to date
Traceback (most recent call last):
	34: from /usr/local/Cellar/fastlane/2.163.0/libexec/bin/fastlane:23:in `<main>'
	33: from /usr/local/Cellar/fastlane/2.163.0/libexec/bin/fastlane:23:in `load'
	32: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/bin/fastlane:23:in `<top (required)>'
	31: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	30: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	29: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	28: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	27: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	26: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	25: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	24: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	23: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	22: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	21: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	20: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	19: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	18: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	17: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	16: from Fastfile:8:in `block (2 levels) in parsing_binding'
	15: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	14: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	13: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	12: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	11: from Fastfile:31:in `block (2 levels) in parsing_binding'
	10: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	 9: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	 8: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	 7: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	 6: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 5: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 4: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 3: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-plugin-huawei_appgallery_connect-1.0.15/lib/fastlane/plugin/huawei_appgallery_connect/actions/huawei_appgallery_connect_submit_for_review.rb:14:in `run'
	 2: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-plugin-huawei_appgallery_connect-1.0.15/lib/fastlane/plugin/huawei_appgallery_connect/helper/huawei_appgallery_connect_helper.rb:282:in `submit_app_for_review'
	 1: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': {"ret"=>{"code"=>204144647, "msg"=>"[cds]update service failed, additional msg is [The new service has can't be edited service,which can't be updated!]"}} (FastlaneCore::Interface::FastlaneError)
	34: from /usr/local/Cellar/fastlane/2.163.0/libexec/bin/fastlane:23:in `<main>'
	33: from /usr/local/Cellar/fastlane/2.163.0/libexec/bin/fastlane:23:in `load'
	32: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/bin/fastlane:23:in `<top (required)>'
	31: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	30: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	29: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	28: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	27: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	26: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	25: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	24: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	23: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	22: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	21: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	20: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	19: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	18: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	17: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	16: from Fastfile:8:in `block (2 levels) in parsing_binding'
	15: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	14: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	13: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	12: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	11: from Fastfile:31:in `block (2 levels) in parsing_binding'
	10: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	 9: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	 8: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	 7: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	 6: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 5: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 4: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 3: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-plugin-huawei_appgallery_connect-1.0.15/lib/fastlane/plugin/huawei_appgallery_connect/actions/huawei_appgallery_connect_submit_for_review.rb:14:in `run'
	 2: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-plugin-huawei_appgallery_connect-1.0.15/lib/fastlane/plugin/huawei_appgallery_connect/helper/huawei_appgallery_connect_helper.rb:282:in `submit_app_for_review'
	 1: from /usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/usr/local/Cellar/fastlane/2.163.0/libexec/gems/fastlane-2.165.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': \e[31m[!] {"ret"=>{"code"=>204144647, "msg"=>"[cds]update service failed, additional msg is [The new service has can't be edited service,which can't be updated!]"}}\e[0m (FastlaneCore::Interface::FastlaneError)

```

**Comment by shr3jn** [comment]
You are submitting app for review multiple times, thats the reason the second command is failing. Please check the documentation.

**Comment by minkiapps** [comment]
Hey, I tried now all steps in Postman
- Obtain Auth Token
- Get Publisher Url
- Update aab file info
- Query compilation status
- Submit App

its working fine, I noticed that you add some url param to `https://connect-api.cloud.huawei.com/api/publish/v2/app-submit&appId=12345`, for me it worked without problem by only adding appId

could you check what POST url you are sending at last step if no any additional parameter (e.g.: phased release, release date) in fastlane file?

**Comment by shr3jn** [comment]
Please post your fastfile.

**Comment by minkiapps** [comment]
```
default_platform(:android)

platform :android do
  desc "build and deploy to AGC"
    lane :deployBundleRelease do
        makeReleaseBundle
        uploadBundleHuaweiRelease
        submitAppOnAGC
    end

  desc "bump version, commit and build aab"
    lane :makeReleaseBundle do
        increment_version_code
        commit_android_version_bump
        gradle(task: "clean bundleRelease")
    end

  desc "Deploy a new release version to the Huawei App Gallery Connect"
      lane :uploadBundleHuaweiRelease do
        huawei_appgallery_connect(
            client_id: "1123123123123",
            client_secret: "12345213421341234123",
            app_id: "2341234",
            apk_path: "12342134213421342134/minki/code/android/Instant-Translator/app/build/outputs/bundle/release/app-release.aab",
            is_aab: true
        )
      end

  desc "submit app in app gallery"
    lane :submitAppOnAGC do
        huawei_appgallery_connect_submit_for_review(
            client_id: "1234123421344231",
            client_secret: "12342134213421342134",
            app_id: "123412342134",
        )
      end
end
```

**Comment by shr3jn** [comment]
You can add the following on your _uploadBundleHuaweiRelease_ lane. This should fix the problem. But anyways, releasing a new version which should also by default not submit the app for review.
`submit_for_review: false`

**Comment by minkiapps** [comment]
but I actually want to straight submit for review, thats the point

**Comment by shr3jn** [comment]
Remove the second lane, that is just submitting the app again for review which is causing the problem in the furst place.

**Comment by shr3jn** [comment]
uploadBundleHuaweiRelease is already submitting the app for review, submitAppOnAGC is again trying to submit for review. So remove the later one.

**Comment by minkiapps** [comment]
aaahhh I see, thanks!

really cool, we finally have a working solution in fastlane for aab upload
great thanks, I will promote your plugin internally now in Huawei :) 

Could you meanwhile tweak the polling interval and also change the UI message -> see my comments in your commit
