### ISSUE TITLE
Specified `release_time` throws "Expected Class (String or Addressable::URI), got /\W/"

### ISSUE THREAD

**Issue by Mol0ko** [shr3jn/fastlane-plugin-huawei_appgallery_connect#41]
Hi! Got an error when trying to submit an app for review with `release_time`.

My lane:
```
lane :huawei_app_gallery_prod do
	huawei_appgallery_connect(
		client_id: ***,
		client_secret: ***,
		app_id: ***,
		apk_path: ***,
		is_aab: true,
		delay_before_submit_for_review: 30,
		submit_for_review: true,
		release_time: DateTime.now().next_day(2).to_s
	)
end
```

Plugin version: `1.0.23`
Fastlane version: `2.209.1`

Action log:
```
129+-------------------------------------------+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
130|                                                                                                      Used plugins                                                                                                       |
131+-------------------------------------------+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
132| Plugin                                    | Version | Action                                                                                                                                                            |
133+-------------------------------------------+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
134| fastlane-plugin-huawei_appgallery_connect | 1.0.23  | huawei_appgallery_connect_update_app_localization, huawei_appgallery_connect_submit_for_review, huawei_appgallery_connect, huawei_appgallery_connect_get_app_info |
135+-------------------------------------------+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
136[03:09:05]: Driving the lane 'huawei_app_gallery_prod' 🚀
137[03:09:05]: ---------------------------------------
138[03:09:05]: --- Step: huawei_appgallery_connect ---
139[03:09:05]: ---------------------------------------
140[03:09:05]: Fetching app access token
141[03:09:06]: Fetching upload URL
142[03:09:07]: Uploading app
143[03:09:14]: Upload app to AppGallery Connect successful
144[03:09:14]: Saving app information
145[03:09:16]: App information saved.
146[03:09:16]: Waiting 30 seconds for upload to get processed...
147[03:09:46]: Checking aab compilation status
148[03:09:46]: aab file is currently processing, waiting for 2 minutes...
149[03:11:46]: Checking aab compilation status
150[03:11:47]: Submitting app for review
151+---------------+-------------------------+
152|              Lane Context               |
153+---------------+-------------------------+
154| PLATFORM_NAME |                         |
155| LANE_NAME     | huawei_app_gallery_prod |
156+---------------+-------------------------+
157[03:11:47]: Expected Class (String or Addressable::URI), got /\W/
158+------+---------------------------+-------------+
159|                fastlane summary                |
160+------+---------------------------+-------------+
161| Step | Action                    | Time (in s) |
162+------+---------------------------+-------------+
163| 💥   | huawei_appgallery_connect | 161         |
164+------+---------------------------+-------------+
165[03:11:47]: fastlane finished with errors
166Looking for related GitHub issues on fastlane/fastlane...
167➡️  can't modify frozen String: "true" for enterprise builds
168    https://github.com/fastlane/fastlane/issues/16055 [closed] 42 💬
169    11 Jul 2020
170🔗  You can ⌘ + double-click on links to open them directly in your browser.
171bundler: failed to load command: fastlane (/Users/administrator/.gem/bin/fastlane)
172/Users/administrator/.gem/gems/addressable-2.8.1/lib/addressable/uri.rb:619:in `encode': [!] Expected Class (String or Addressable::URI), got /\W/ (TypeError)
173	from /Users/administrator/.gem/gems/fastlane-plugin-huawei_appgallery_connect-1.0.23/lib/fastlane/plugin/huawei_appgallery_connect/helper/huawei_appgallery_connect_helper.rb:231:in `submit_app_for_review'
174	from /Users/administrator/.gem/gems/fastlane-plugin-huawei_appgallery_connect-1.0.23/lib/fastlane/plugin/huawei_appgallery_connect/actions/huawei_appgallery_connect_action.rb:40:in `submit_for_review'
175	from /Users/administrator/.gem/gems/fastlane-plugin-huawei_appgallery_connect-1.0.23/lib/fastlane/plugin/huawei_appgallery_connect/actions/huawei_appgallery_connect_action.rb:38:in `submit_for_review'
176	from /Users/administrator/.gem/gems/fastlane-plugin-huawei_appgallery_connect-1.0.23/lib/fastlane/plugin/huawei_appgallery_connect/actions/huawei_appgallery_connect_action.rb:26:in `run'
```

Are you sure about this line?
https://github.com/shr3jn/fastlane-plugin-huawei_appgallery_connect/blob/c58a9fecc4bbf9948536a2751003ae53e444b4c6/lib/fastlane/plugin/huawei_appgallery_connect/helper/huawei_appgallery_connect_helper.rb#L231

Thanks!

**Comment by shr3jn** [comment]
Fixed on v1.0.24
