### ISSUE TITLE
Timeout issue when uploading the app.

### ISSUE THREAD

**Issue by ptfly** [shr3jn/fastlane-plugin-huawei_appgallery_connect#44]
I was having an issue with WriteTimeouts when trying to upload. Had to add `write_timeout` with some reasonable value in order to make it work.

`huawei_appgallery_connect_helper.rb` (`upload_app` method) line `96`:
```
http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true
http.write_timeout = 120  #in seconds

**Comment by shr3jn** [comment]
Please post the exact error message that you receive in order to trace the issue.

**Comment by codestation** [comment]
I am also having multiple timeouts while uploading the files

```
/usr/lib/ruby/3.0.0/net/protocol.rb:298:in `block in write0': Net::WriteTimeout with #<Socket:(closed)> (Net::WriteTimeout)
        from /usr/lib/ruby/3.0.0/net/protocol.rb:277:in `each'
        from /usr/lib/ruby/3.0.0/net/protocol.rb:277:in `each_with_index'
        from /usr/lib/ruby/3.0.0/net/protocol.rb:277:in `write0'
        from /usr/lib/ruby/3.0.0/net/protocol.rb:250:in `block in write'
        from /usr/lib/ruby/3.0.0/net/protocol.rb:267:in `writing'
        from /usr/lib/ruby/3.0.0/net/protocol.rb:249:in `write'
        from /usr/lib/ruby/3.0.0/net/http/generic_request.rb:230:in `copy_stream'
        from /usr/lib/ruby/3.0.0/net/http/generic_request.rb:230:in `send_request_with_body_data'
        from /usr/lib/ruby/3.0.0/net/http/generic_request.rb:127:in `exec'
        from /usr/lib/ruby/3.0.0/net/http.rb:1608:in `block in transport_request'
        from /usr/lib/ruby/3.0.0/net/http.rb:1606:in `catch'
        from /usr/lib/ruby/3.0.0/net/http.rb:1606:in `transport_request'
        from /usr/lib/ruby/3.0.0/net/http.rb:1579:in `request'
        from /usr/lib/ruby/3.0.0/net/http.rb:1572:in `block in request'
        from /usr/lib/ruby/3.0.0/net/http.rb:985:in `start'
        from /usr/lib/ruby/3.0.0/net/http.rb:1570:in `request'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/fastlane-plugin-huawei_appgallery_connect-1.0.27/lib/fastlane/plugin/huawei_appgallery_connect/helper/huawei_appgallery_connect_helper.rb:157:in `upload_app'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/fastlane-plugin-huawei_appgallery_connect-1.0.27/lib/fastlane/plugin/huawei_appgallery_connect/actions/huawei_appgallery_connect_action.rb:18:in `run'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:149:in `block (3 levels) in parsing_binding'
        from Fastfile:143:in `each'
        from Fastfile:143:in `block (2 levels) in parsing_binding'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/bin/fastlane:23:in `<top (required)>'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/bin/fastlane:25:in `load'
        from /home/code/assetec/edificia-webview/vendor/bundle/ruby/3.0.0/bin/fastlane:25:in `<top (required)>'
        from /usr/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `load'
        from /usr/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/lib/ruby/3.0.0/bundler/cli/exec.rb:23:in `run'
        from /usr/lib/ruby/3.0.0/bundler/cli.rb:492:in `exec'
        from /usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/lib/ruby/3.0.0/bundler/cli.rb:34:in `dispatch'
        from /usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/lib/ruby/3.0.0/bundler/cli.rb:28:in `start'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.4.20/exe/bundle:37:in `block in <top (required)>'
        from /usr/lib/ruby/3.0.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.4.20/exe/bundle:29:in `<top (required)>'
        from /usr/bin/bundle:25:in `load'
        from /usr/bin/bundle:25:in `<main>'
```

**Comment by codestation** [comment]
I am also getting multiple write errors

```
/usr/lib/ruby/3.0.0/net/protocol.rb:298:in `block in write0': Net::WriteTimeout with #<Socket:(closed)> (Net::WriteTimeout)
        from /usr/lib/ruby/3.0.0/net/protocol.rb:277:in `each'
        from /usr/lib/ruby/3.0.0/net/protocol.rb:277:in `each_with_index'
        from /usr/lib/ruby/3.0.0/net/protocol.rb:277:in `write0'
        from /usr/lib/ruby/3.0.0/net/protocol.rb:250:in `block in write'
        from /usr/lib/ruby/3.0.0/net/protocol.rb:267:in `writing'
        from /usr/lib/ruby/3.0.0/net/protocol.rb:249:in `write'
        from /usr/lib/ruby/3.0.0/net/http/generic_request.rb:230:in `copy_stream'
        from /usr/lib/ruby/3.0.0/net/http/generic_request.rb:230:in `send_request_with_body_data'
        from /usr/lib/ruby/3.0.0/net/http/generic_request.rb:127:in `exec'
        from /usr/lib/ruby/3.0.0/net/http.rb:1608:in `block in transport_request'
        from /usr/lib/ruby/3.0.0/net/http.rb:1606:in `catch'
        from /usr/lib/ruby/3.0.0/net/http.rb:1606:in `transport_request'
        from /usr/lib/ruby/3.0.0/net/http.rb:1579:in `request'
        from /usr/lib/ruby/3.0.0/net/http.rb:1572:in `block in request'
        from /usr/lib/ruby/3.0.0/net/http.rb:985:in `start'
        from /usr/lib/ruby/3.0.0/net/http.rb:1570:in `request'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/fastlane-plugin-huawei_appgallery_connect-1.0.27/lib/fastlane/plugin/huawei_appgallery_connect/helper/huawei_appgallery_connect_helper.rb:157:in `upload_app'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/fastlane-plugin-huawei_appgallery_connect-1.0.27/lib/fastlane/plugin/huawei_appgallery_connect/actions/huawei_appgallery_connect_action.rb:18:in `run'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:149:in `block (3 levels) in parsing_binding'
        from Fastfile:143:in `each'
        from Fastfile:143:in `block (2 levels) in parsing_binding'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.216.0/bin/fastlane:23:in `<top (required)>'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/bin/fastlane:25:in `load'
        from /home/code/projects/app/vendor/bundle/ruby/3.0.0/bin/fastlane:25:in `<top (required)>'
        from /usr/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `load'
        from /usr/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/lib/ruby/3.0.0/bundler/cli/exec.rb:23:in `run'
        from /usr/lib/ruby/3.0.0/bundler/cli.rb:492:in `exec'
        from /usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/lib/ruby/3.0.0/bundler/cli.rb:34:in `dispatch'
        from /usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/lib/ruby/3.0.0/bundler/cli.rb:28:in `start'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.4.20/exe/bundle:37:in `block in <top (required)>'
        from /usr/lib/ruby/3.0.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.4.20/exe/bundle:29:in `<top (required)>'
        from /usr/bin/bundle:25:in `load'
        from /usr/bin/bundle:25:in `<main>'
```
