### ISSUE TITLE
Changelog containg semicolon fails submiting app to review

### ISSUE THREAD

**Issue by marekkondracki** [shr3jn/fastlane-plugin-huawei_appgallery_connect#45]
I upload my app with changelog containg semicolon, then lane fails.
text:
```
Zmiany w wersji 3.0.3:
```

Stacktrace:
```
bundler: failed to load command: fastlane (/home/jenkins_mobile/.gem/ruby/2.5.0/bin/fastlane)
Addressable::URI::InvalidURIError: [!] Invalid scheme format: Zmiany w wersji 3.0.7
  /home/jenkins_mobile/.gem/ruby/2.5.0/gems/addressable-2.7.0/lib/addressable/uri.rb:901:in `scheme='
  /home/jenkins_mobile/.gem/ruby/2.5.0/gems/addressable-2.7.0/lib/addressable/uri.rb:826:in `block in initialize'
  /home/jenkins_mobile/.gem/ruby/2.5.0/gems/addressable-2.7.0/lib/addressable/uri.rb:2392:in `defer_validation'
  /home/jenkins_mobile/.gem/ruby/2.5.0/gems/addressable-2.7.0/lib/addressable/uri.rb:823:in `initialize'
  /home/jenkins_mobile/.gem/ruby/2.5.0/gems/addressable-2.7.0/lib/addressable/uri.rb:138:in `new'
  /home/jenkins_mobile/.gem/ruby/2.5.0/gems/addressable-2.7.0/lib/addressable/uri.rb:138:in `parse'
  /home/jenkins_mobile/.gem/ruby/2.5.0/gems/addressable-2.7.0/lib/addressable/uri.rb:607:in `encode'
  /home/jenkins_mobile/.gem/ruby/2.5.0/gems/fastlane-plugin-huawei_appgallery_connect-1.0.23/lib/fastlane/plugin/huawei_appgallery_connect/helper/huawei_appgallery_connect_helper.rb:244:in `submit_app_for_review'
  /home/jenkins_mobile/.gem/ruby/2.5.0/gems/fastlane-plugin-huawei_appgallery_connect-1.0.23/lib/fastlane/plugin/huawei_appgallery_connect/actions/huawei_appgallery_connect_action.rb:40:in `submit_for_review'
  /home/jenkins_mobile/.gem/ruby/2.5.0/gems/fastlane-plugin-huawei_appgallery_connect-1.0.23/lib/fastlane/plugin/huawei_appgallery_connect/actions/huawei_appgallery_connect_action.rb:26:in `run'
  ```

**Comment by shr3jn** [comment]
Fixed on v1.0.24
