### ISSUE TITLE
Invalid argument @ io_fread - project.apk (Errno::EINVAL)

### ISSUE THREAD

**Issue by yoshikakbudto** [shr3jn/fastlane-plugin-huawei_appgallery_connect#69]
Can't upload to Huawei because of the misterious error Errno:EINVAL
The apk file is readable and correct.

The Fastfile config is:
```ruby
#!/usr/bin/ruby

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# skip generating README.md
skip_docs

default_platform(:android)

platform :android do
lane :test do
  huawei_appgallery_connect(
    client_id: "15...cut-cut-cut-8",
    client_secret: "FE.cut-cut-cut-..C",
    app_id: "10..cut-cut-cut-.5",
    apk_path: "project.apk",

    submit_for_review: false,

  )
end


end

```

```
# fastlane test


[✔] 🚀
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                              Used plugins                                                                               |
+-------------------------------------------+---------+-------------------------------------------------------------------------------------------------------------------+
| Plugin                                    | Version | Action                                                                                                            |
+-------------------------------------------+---------+-------------------------------------------------------------------------------------------------------------------+
| fastlane-plugin-huawei_appgallery_connect | 1.0.31  | huawei_appgallery_connect_update_app_localization, huawei_appgallery_connect_submit_for_review,                   |
|                                           |         | huawei_appgallery_connect_set_gms_dependency, huawei_appgallery_connect, huawei_appgallery_connect_get_app_info,  |
|                                           |         | huawei_appgallery_connect_get_app_id                                                                              |
+-------------------------------------------+---------+-------------------------------------------------------------------------------------------------------------------+

------------------------------
--- Step: default_platform ---
------------------------------
Driving the lane 'android test' 🚀
---------------------------------------
--- Step: huawei_appgallery_connect ---
---------------------------------------
Fetching app access token
Fetching upload URL
Uploading app
+---------------------------------+
|          Lane Context           |
+------------------+--------------+
| DEFAULT_PLATFORM | android      |
| PLATFORM_NAME    | android      |
| LANE_NAME        | android test |
+------------------+--------------+
Called from Fastfile at line 43
```
    41:
    42: lane :test do
 => 43:   huawei_appgallery_connect(
    44:     client_id: "1519754360651816128",
    45:     client_secret: "FE26EFF2144F3546A8D42B2CF170EA55B7F7316C878545001772FF4B89B601DC",
```
Invalid argument @ io_fread - /Users/builduser/huawei_deploy_fastlane/project.apk
fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):
        30: from /Users/builduser/.rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `<main>'
        29: from /Users/builduser/.rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `eval'
        28: from /Users/builduser/.rvm/gems/ruby-2.7.4/bin/fastlane:25:in `<main>'
        27: from /Users/builduser/.rvm/gems/ruby-2.7.4/bin/fastlane:25:in `load'
        26: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-2.222.0/bin/fastlane:23:in `<top (required)>'
        25: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-2.222.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        24: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        23: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
        22: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        21: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-2.222.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        20: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        19: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        18: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        17: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        16: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-2.222.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
        15: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-2.222.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
        14: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        13: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        12: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        11: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-2.222.0/fastlane/lib/fastlane/lane.rb:41:in `call'
        10: from Fastfile:43:in `block (2 levels) in parsing_binding'
         9: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-2.222.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
         8: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
         7: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
         6: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
         5: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
         4: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-2.222.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
         3: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
         2: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-plugin-huawei_appgallery_connect-1.0.31/lib/fastlane/plugin/huawei_appgallery_connect/actions/huawei_appgallery_connect_action.rb:18:in `run'
         1: from /Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-plugin-huawei_appgallery_connect-1.0.31/lib/fastlane/plugin/huawei_appgallery_connect/helper/huawei_appgallery_connect_helper.rb:165:in `upload_app'
/Users/builduser/.rvm/gems/ruby-2.7.4/gems/fastlane-plugin-huawei_appgallery_connect-1.0.31/lib/fastlane/plugin/huawei_appgallery_connect/helper/huawei_appgallery_connect_helper.rb:165:in `read': \e[31m[!] Invalid argument @ io_fread - /Users/builduser/huawei_deploy_fastlane/project.apk\e[0m (Errno::EINVAL)
```

**Comment by shr3jn** [comment]
please notify if this error is occuring again.

**Comment by yoshikakbudto** [comment]
Well, nothing has changed. The error is the same:

```
[✔] 🚀
+---------------------------------------------------------------------------------------------------------------------------------+
|                                                          Used plugins                                                           |
+-------------------------------------------+---------+---------------------------------------------------------------------------+
| Plugin                                    | Version | Action                                                                    |
+-------------------------------------------+---------+---------------------------------------------------------------------------+
| fastlane-plugin-huawei_appgallery_connect | 1.1.1   | huawei_appgallery_connect_update_app_localization,                        |
|                                           |         | huawei_appgallery_connect_submit_for_review,                              |
|                                           |         | huawei_appgallery_connect_set_gms_dependency, huawei_appgallery_connect,  |
|                                           |         | huawei_appgallery_connect_get_app_info,                                   |
|                                           |         | huawei_appgallery_connect_get_app_id                                      |
+-------------------------------------------+---------+---------------------------------------------------------------------------+

[19:32:16]: ------------------------------
[19:32:16]: --- Step: default_platform ---
[19:32:16]: ------------------------------
[19:32:16]: Driving the lane 'android test' 🚀
[19:32:16]: ---------------------------------------
[19:32:16]: --- Step: huawei_appgallery_connect ---
[19:32:16]: ---------------------------------------
[19:32:16]: Fetching app access token
[19:32:16]: Fetching upload URL
[19:32:21]: Uploading app
+---------------------------------+
|          Lane Context           |
+------------------+--------------+
| DEFAULT_PLATFORM | android      |
| PLATFORM_NAME    | android      |
| LANE_NAME        | android test |
+------------------+--------------+
[19:32:21]: Called from Fastfile at line 7
[19:32:21]: ```
[19:32:21]:     5:      platform :android do
[19:32:21]:     6:          lane :test do
[19:32:21]:  => 7:            huawei_appgallery_connect(
[19:32:21]:     8:              client_id: "1519754360651816128",
[19:32:21]:     9:              client_secret: "FE26EFF2144F3546A8D42B2CF170EA55B7F7316C878545001772FF4B89B601DC",
[19:32:21]: ```
[19:32:21]: Invalid argument @ io_fread - /Users/builduser/huawei_deploy_fastlane/fastlane/project.apk

+------------------------------------------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | default_platform          | 0           |
| 💥   | huawei_appgallery_connect | 5           |
+------+---------------------------+-------------+

[19:32:21]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):
        30: from /Users/builduser/.rvm/gems/ruby-2.7.8/bin/ruby_executable_hooks:22:in `<main>'
        29: from /Users/builduser/.rvm/gems/ruby-2.7.8/bin/ruby_executable_hooks:22:in `eval'
        28: from /Users/builduser/.rvm/gems/ruby-2.7.8/bin/fastlane:23:in `<main>'
        27: from /Users/builduser/.rvm/gems/ruby-2.7.8/bin/fastlane:23:in `load'
        26: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-2.228.0/bin/fastlane:23:in `<top (required)>'
        25: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-2.228.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        24: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-2.228.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        23: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-2.228.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
        22: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        21: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-2.228.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        20: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        19: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        18: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        17: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-2.228.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        16: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-2.228.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
        15: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-2.228.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
        14: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-2.228.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        13: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-2.228.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        12: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-2.228.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        11: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-2.228.0/fastlane/lib/fastlane/lane.rb:41:in `call'
        10: from Fastfile:7:in `block (2 levels) in parsing_binding'
         9: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-2.228.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
         8: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-2.228.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
         7: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-2.228.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
         6: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-2.228.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
         5: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-2.228.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
         4: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-2.228.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
         3: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-2.228.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
         2: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-plugin-huawei_appgallery_connect-1.1.1/lib/fastlane/plugin/huawei_appgallery_connect/actions/huawei_appgallery_connect_action.rb:17:in `run'
         1: from /Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-plugin-huawei_appgallery_connect-1.1.1/lib/fastlane/plugin/huawei_appgallery_connect/helper/huawei_appgallery_connect_helper.rb:166:in `upload_app'
/Users/builduser/.rvm/gems/ruby-2.7.8/gems/fastlane-plugin-huawei_appgallery_connect-1.1.1/lib/fastlane/plugin/huawei_appgallery_connect/helper/huawei_appgallery_connect_helper.rb:166:in `read': \e[31m[!] Invalid argument @ io_fread - /Users/builduser/huawei_deploy_fastlane/fastlane/project.apk\e[0m (Errno::EINVAL)

```
