### ISSUE TITLE
Error uploading

### ISSUE THREAD

**Issue by zkrige** [shr3jn/fastlane-plugin-huawei_appgallery_connect#9]
```
1: from /usr/local/Cellar/fastlane/2.141.0/libexec/gems/fastlane-plugin-huawei_appgallery_connect-1.0.5/lib/fastlane/plugin/huawei_appgallery_connect/actions/huawei_appgallery_connect_action.rb:18:in `run'
/usr/local/Cellar/fastlane/2.141.0/libexec/gems/fastlane-plugin-huawei_appgallery_connect-1.0.5/lib/fastlane/plugin/huawei_appgallery_connect/helper/huawei_appgallery_connect_helper.rb:125:in `upload_app': [!] undefined method `[]' for nil:NilClass (NoMethodError)

```

**Comment by shr3jn** [comment]
Please try with v1.0.6, added check for HTTP status.

**Comment by shr3jn** [comment]
Issue close due to inactivity.
